# Clan settings.
Settings:
  # Tempo para sincronizar
  # servidor - database.
  update-interval: 5 # Em minutos.

  # Caso uma variavel boolean
  # seja, true.
  boolean-true: "&aOn"
  # Caso uma variavel boolean
  # seja, false.
  boolean-false: "&cOff"

  # <----- -----> #
  # Abaixo está a configuração
  # dos clans.
  # <----- -----> #

  # Quantidade máxima de
  # caracteres que a
  # tag do clan pode ter.
  clan-max-tag-size: 16

  # Quantidade minima que
  # a tag do clan deve
  # ter.
  clan-min-tag-size: 3

  # Quantidade máxima de
  # caracteres no nome
  # do clan.
  clan-name-max-size: 32

  # Quantidade minima que
  # o nome do clan deve ter.
  clan-name-min-size: 7

  # Quantidade máxima de jogadores
  # por clan.
  clan-max-members: 32

  # Classificação entre os
  # jogadores do mesmo clan,
  # quantidade de membros
  # que será apresentado.
  member-leaderboard-limit: 3

  # Máximo de aliado e/ou
  # rival que o clan pode ter.
  clan-relations-size: 10

  # Classificação entre os
  # clans do servidor,
  # quantos clans
  # será apresentado.
  clan-leaderboad-limit: 10

  # Tempo para expirar convites.
  invite-expiration-time: 5 # Em minutos.

# Configurações dos Cargos.
Roles:
  # owner - representa o dono
  # do clan.
  owner:
    name: "DONO" # Nome do cargo.
    color: "&4" # Cor do cargo.

  # officer - representa o adminstrador
  # do clan.
  officer:
    name: "ADMIN"
    color: "&c"

  # member - representa os membros
  # do clan.
  member:
    name: "MEMBRO"
    color: "&7"

# Mensagens.
Messages:
  # Criação/Editar clan.
  already-has-clan: "&cVocê já possui clan."
  invalid-name-or-tag: "&cEste nome ou tag não é válido."
  name-already-in-use: "&cEste nome já está em uso."
  tag-already-in-use: "&cEsta tag já está em uso."
  invalid-name-size: "&cO nome do clan deve ter entre &f%max_length% &ce &f%min_length%&c."
  invalid-tag-size: "&cA tag do clan deve ter entre &f%max_length% &ce &f%min_length%&c."
  invalid-characters: "&cO nome/tag do seu clan possui caracteres inválidos."

  clan-created: "&aVocê criou um novo clan."

Broadcast:
  new-clan-created: # Para remover esta mensagem, apenas apague as linhas abaixo e adicione "{}" na frente de "new-clan-created:";
    - '&8--------------------'
    - '&aNovo clan criado, NOME: ''%sky_clan_name%'', TAG: ''%sky_clan_tag%''.'
    - '&8--------------------'

# Mensagens dos comandos.
Commands:
  only-players: "&cApenas jogadores podem executar este comando."

  create-clan-help: "&cUse: &e/clan criar/create <nome> <tag> <descrição> &b: Criar novo clan."

  # Help-me.
  help:
    - '&6-------------------------'
    - ''
    - '&aComandos do Clan:'
    - '&e/clan &b: Abrir menu principal.'
    - '&e/clan criar/create <nome> <tag> <descrição> &b: Criar novo clan.'
    - '&e/clan top &b: Ver a lista dos melhores clans.'
    - '&e/clan jogador/perfil/player <jogador> &b: Ver informações do jogador.'
    - '&e/clan clan <tag> &b: Ver informações do clan.'
    - '&e/clan rivalidades/rivals &b: Ver lista de rivalidades.'
    - '&e/clan aliancas/alianças/allies &b: Ver lista de aliados.'
    - '&e/clan membros/members &b: Ver membros do clan.'
    - '&e/clan promover/promote <jogador> &b: Promover um jogador.'
    - '&e/clan rebaixar/demote <jogador> &b: Rebaixar o cargo de um jogador.'
    - '&e/clan lista/list &b: Ver a lista de clans criados.'
    - '&e/clan convidar/invite &b: Convidar um jogador para o clan.'
    - '&e/clan expulsar/kick <jogador> &b: Expulsar um jogador do clan.'
    - '&e/clan desfazer/excluir/delete &b: Deleter o clan.'
    - '&e/clan aliado/ally (add/adicionar&7-&eremover/del) &b: Adicionar/Remover um aliado.'
    - '&e/clan rival (add/adicionar&7-&eremover/del) &b: Adicionar/Remover um rival.'
    - '&e/clan pvp &b: Ativar/Desativar pvp entre os membros do clan.'
    - ''
    - '&6-------------------------'

# Formatação de números.
NumberFormat:
  thousand: "k"
  million: "m"
  billion: "b"
  trillion: "t"
  quadrillion: "q"
  quintillion: "q"
  # Você pode adicionar
  # mais formatações abaixo.