# Clan settings.
Settings:
  # Tempo para sincronizar
  # servidor - database.
  update-interval: 5 # Em minutos.

  # Caso uma variavel boolean
  # seja, true.
  boolean-true: "&aOn"
  # Caso uma variavel boolean
  # seja, false.
  boolean-false: "&cOff"

  # Formatação do chat do clan.
  clan-chat-format: "&8[%skyclan_clan_tag%&8] %player_name%: &f%message%"

  # Formatação dos dia/horário.
  date-format-pattern: "dd/MM/yyyy - hh:mm"

  # <----- -----> #
  # Abaixo está a configuração
  # dos clans.
  # <----- -----> #

  # Quantidade máxima de
  # caracteres que a
  # tag do clan pode ter.
  clan-max-tag-size: 16

  # Quantidade minima que
  # a tag do clan deve
  # ter.
  clan-min-tag-size: 3

  # Quantidade máxima de
  # caracteres no nome
  # do clan.
  clan-name-max-size: 32

  # Quantidade minima que
  # o nome do clan deve ter.
  clan-name-min-size: 7

  # Quantidade máxima de jogadores
  # por clan.
  clan-max-members: 32

  # Classificação entre os
  # jogadores do mesmo clan,
  # quantidade de membros
  # que será apresentado.
  member-leaderboard-limit: 3

  # Máximo de aliado e/ou
  # rival que o clan pode ter.
  clan-relations-size: 10

  # Classificação entre os
  # clans do servidor,
  # quantos clans
  # será apresentado.
  clan-leaderboad-limit: 15

  # Tempo para expirar convites.
  invite-expiration-time: 5 # Em minutos.

# Configurações dos nomes
# das classificações.
Leaderboard:
  kills:
    name: "abates"
  deaths:
    name: "mortes"
  kdr:
    name: "kdr"

# Configurações dos Cargos.
Roles:
  # owner - representa o dono
  # do clan.
  owner:
    name: "DONO" # Nome do cargo.
    color: "&4" # Cor do cargo.

  # officer - representa o adminstrador
  # do clan.
  officer:
    name: "ADMIN"
    color: "&c"

  # member - representa os membros
  # do clan.
  member:
    name: "MEMBRO"
    color: "&7"

  unranked:
    name: "SEM CLAN"
    color: "&8"

# Mensagens.
Messages:
  cannot-execute-yourself: "&cVocê não pode realizar isso para sí mesmo."
  role-required: "&cVocê precisa ser %skyclan_member_role% &cou superior."
  not-in-clan: "&cVocê não possui Clan."
  clan-not-found: "&cNão foi possível encontrar este Clan."
  target-not-found: "&cNão foi possível encontrar este jogador."
  player-not-online: "&cEste jogador não está online."
  target-not-on-same-clan: "&cEste jogador não é membro do seu Clan."
  target-has-clan-already: "&cEste jogador já possui Clan."
  already-has-clan: "&cVocê já possui clan."
  target-has-higher-role: "&cEste jogador possui um cargo maior!"
  # Criação/Editar clan.
  invalid-name-or-tag: "&cEste nome ou tag não é válido."
  name-already-in-use: "&cEste nome já está em uso."
  tag-already-in-use: "&cEsta tag já está em uso."
  invalid-name-size: "&cO nome do clan deve ter entre &f%max_length% &ce &f%min_length%&c."
  invalid-tag-size: "&cA tag do clan deve ter entre &f%max_length% &ce &f%min_length%&c."
  invalid-characters: "&cO nome/tag do seu clan possui caracteres inválidos."
  clan-created: "&aVocê criou um novo clan."
  # Clan player comando.
  target-clan-not-found: "&cEste jogador não possui clan."
  # Comando de promover/rebaixar.
  promote-player-sender: "&7Você promoveu o jogador %target_name% para %skyclan_member_role%!" # Quem promoveu o jogador.
  promote-player-target: "&6Você foi promovido para %skyclan_member_role%&6!" # Jogador que foi promovido.
  promote-player-broadcast: # Para todos os membros do Clan.
    - '&8--------------------'
    - '&7O Jogador &3%target_name% &7foi promovido para %skyclan_member_role%&7!'
    - '&8--------------------'
  demote-player-sender: "&7Você rebaixou o jogador %target_name% para %skyclan_member_role%!" # Quem rebaixou o jogador.
  demote-player-target: "&6Você foi rebaixado para %skyclan_member_role%&6!" # Jogador que foi rebaixado.
  demote-player-broadcast: # Para todos os membros do Clan.
    - '&8--------------------'
    - '&7O Jogador &3%target_name% &7foi rebaixado para %skyclan_member_role%&7!'
    - '&8--------------------'
  # Comando de convidar.
  target-is-member-already: "&cEste jogador já faz parte do seu Clan."
  invite-player-sender: "&7Você convidou o jogador %target_name% para seu Clan, ele tem &c5min &7para aceitar." # Quem convidou o jogador.
  invite-player-target: "&8Você foi convidado para juntar-se à %skyclan_clan_tag%&8. &cVocê tem 5min para aceitar." # Jogador que foi convidado.
  # Comando de aceitar clan.
  you-were-not-invited: "&cVocê não foi convidado."
  join-clan-target: "&7Você agora é um novo membro do Clan ''%skyclan_clan_tag%''" # Jogador que entrou no clan.
  join-clan-broadcast: # Para todos os membros do Clan.
    - '&8O Jogador %target_name% juntou-se ao Clan!'
  # Comando de expulsar.
  player-kicked-sender: "&aVocê expulsou o jogador %target_name%!" # Quem expulsou o jogador.
  player-kicked-target: "&cVocê foi expulso do Clan!" # Jogador que foi expulso.
  player-kicked-broadcast: # Para todos os membros do Clan.
    - '&cO Jogador %target_name% foi expulso do Clan por %player_name%!'
  # Comando de excluir.
  clan-disbanded-broadcast: # Para todos os membros do Clan.
    - '&cEste Clan foi excluido!'
  # Comando de sair.
  left-clan-sender: "&cVocê saiu do Clan."
  left-clan-broadcast:
    - '&cO jogador %target_name% saiu do Clan.'
  # Comando de aliado e rival.
  clan-is-ally-already: "&aEste clan já é um aliado!"
  clan-is-not-ally: "&cEste clan não faz parte da sua lista de aliados."
  clan-is-rival: "&cEste clan é rival, você precisa remove-lo antes."
  clan-is-rival-already: "&aEste clan já é rival!"
  clan-is-not-rival: "&cEste clan não faz parte da sua lista de rivalidades."
  clan-is-ally: "&cEste clan é aliado, você precisa remove-lo antes."

Broadcast:
  new-clan-created: # Para remover esta mensagem, apenas apague as linhas abaixo e adicione "{}" na frente de "new-clan-created:";
    - '&8--------------------'
    - '&aNovo clan criado, NOME: ''%skyclan_clan_name%'', TAG: ''%skyclan_clan_tag%''.'
    - '&8--------------------'
  clan-disbanded:
    - '&8--------------------'
    - '&cClan, ''%skyclan_clan_tag%'' &cfoi excluido!'
    - '&8--------------------'

# Mensagens dos comandos.
Commands:
  only-players: "&cApenas jogadores podem executar este comando."

  clan-chat-help: "&cUse: &e/. <mensagem>."

  create-clan-help: "&cUse: &e/clan criar/create <nome> <tag> <descrição> &b: Criar novo clan."
  promote-member-help: "&cUse: &e/clan promover/promote <jogador> &b: Promover um jogador."
  demote-member-help: "&cUse: &e/clan rebaixar/demote <jogador> &b: Rebaixar o cargo de um jogador."
  invite-member-help: "&cUse: &e/clan convidar/invite &b: Convidar um jogador para o clan."
  accept-member-help: "&cUse: &e/clan aceitar/accept <tag> &b: Aceitar um convite de clan."
  kick-member-help: "&cUse: &e/clan expulsar/kick <jogador> &b: Expulsar um jogador do clan."
  ally-help: "&cUse: &e/clan aliado/ally (add/adicionar&7-&eremover/del) <tag> &b: Adicionar/Remover um aliado."
  rival-help: "&cUse: &e/clan rival (add/adicionar&7-&eremover/del) <tag> &b: Adicionar/Remover um rival."

  # Comando de aliados.
  no-allies-found: "&cNão foi possível encontrar aliados. (Seu Clan não possui aliados)."
  allies-list: "&7Lista de aliados: &7[&e%skyclan_clan_allies%&7]"

  # Comando de rivais.
  no-rivals-found: "&cNão foi possível encontrar rivais. (Seu Clan não possui rivais)."
  rivals-list: "&7Lista de rivais: &7[&e%skyclan_clan_rivals%&7]"

  # Pvp clan.
  clan-pvp-enabled: "&cPVP entre membros do clan foi habilitado!" # Está mensagem será enviada para todos membros do clan.
  clan-pvp-disabled: "&aPVP entre membros do clan foi desabilitado!" # Está mensagem será enviada para todos membros do clan.

  # Help-me.
  help:
    - '&6-------------------------'
    - ''
    - '&aComandos do Clan:'
    - '&e/clan &b: Abrir menu principal.'
    - '&e/clan criar/create <nome> <tag> <descrição> &b: Criar novo clan.'
    - '&e/clan top &b: Ver a lista dos melhores clans.'
    - '&e/clan jogador/perfil/player <jogador> &b: Ver informações do jogador.'
    - '&e/clan clan/stats <tag> &b: Ver informações do clan.'
    - '&e/clan rivalidades/rivals &b: Ver lista de rivalidades.'
    - '&e/clan aliancas/alianças/allies &b: Ver lista de aliados.'
    - '&e/clan membros/members <tag> &b: Ver membros do clan.'
    - '&e/clan promover/promote <jogador> &b: Promover um jogador.'
    - '&e/clan rebaixar/demote <jogador> &b: Rebaixar o cargo de um jogador.'
    - '&e/clan lista/list &b: Ver a lista de clans criados.'
    - '&e/clan convidar/invite <jogador> &b: Convidar um jogador para o clan.'
    - '&e/clan aceitar/accept <tag> &b: Aceitar um convite de clan.'
    - '&e/clan expulsar/kick <jogador> &b: Expulsar um jogador do clan.'
    - '&e/clan desfazer/excluir/disband &b: Deleter o clan.'
    - '&e/clan sair/leave &b: Sair do Clan.'
    - '&e/clan aliado/ally (adicionar/add&7-&eremover/del) <tag> &b: Adicionar/Remover um aliado.'
    - '&e/clan rival (adicionar/add&7-&eremover/del) <tag> &b: Adicionar/Remover um rival.'
    - '&e/clan pvp &b: Ativar/Desativar pvp entre os membros do clan.'
    - ''
    - '&6-------------------------'

# Formatação de números.
NumberFormat:
  thousand: "k"
  million: "m"
  billion: "b"
  trillion: "t"
  quadrillion: "q"
  quintillion: "q"
  # Você pode adicionar
  # mais formatações abaixo.