name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SkyVox_
website: skydhs.com
softdepend:
  - PlaceholderAPI
  - Legendchat

# The Main class.
main: com.skydhs.czclan.clan.Core

commands:
  clan:
    description: "Interact with your clan."
    usage: "/clan ajuda"
  clanadmin:
    description: "Clan admin command."
    aliases: "ca"
    usage: "/clan ajuda"
  clanchat:
    description: "Sends a message for your clan."
    aliases: "."
    usage: "/. <message>"