name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SkyVox_
website: skydhs.com
softdepend:
  - PlaceholderAPI
  - Legendchat

# The Main class.
main: com.skydhs.czclan.clan.Core

commands:
  clan:
    description: "Use este comando para interagir com seu clan."
    usage: "/clan ajuda"
  clanadmin:
    description: "Use este comando para interagir com os clans."
    aliases: "ca"
    usage: "/clan ajuda"